import React, { useState } from 'react'
import { useRouter } from 'next/router'

const Instructions = () => {
  const [consent, setConsent] = useState(false);

  const [q1, setQ1] = useState(false);
  const [q2, setQ2] = useState(false);
  const [q3, setQ3] = useState(false);
  const [q4, setQ4] = useState(false);

  const router = useRouter();

  const next = () => {
    if (!(q1 && !q2 && !q3 && q4)) {
      alert('Please carefully read the instructions to answer the questions correctly!');
      return;
    }
    router.push('/introduction');
  };

  return (
    <div className="content">
      <h1>Algebra Solutions :: Human Evaluation</h1>
      <p>
        In this experiment, you are going to help us build better algebra tutors.
        These computer tutors can help students learn to solve equations, fractions or other problems.
        But the computer often finds complicated solutions that are hard for students to understand!
        Your task is to compare different solutions generated by a program and choose the one you think would be most clear and helpful for students.
        Completing the entire task takes an average of 10 minutes.`
      </p>

      <p>
        By following the instructions, you are participating in a study being performed by
        cognitive scientists in the Department of Psychology at Stanford University.
        If you have questions about this research, please contact Gabriel Poesia (poesia@stanford.edu)
        or Noah Goodman (ngoodman@stanford.edu).
      </p>

      <h2>Consent</h2>

      <ul>
        <li>You must be at least 18 years old to participate.</li>
        <li>Your participation in this research is voluntary.</li>
        <li>You may decline to answer any or all of the following questions.</li>
        <li>You may decline further participation, at any time, without adverse consequences.</li>
        <li>Your anonymity is assured; the researchers who have requested your participation will not receive any personally identifying information.</li>
      </ul>

      <p>
        <input type="checkbox" value={consent} onChange={() => setConsent(!consent)} />
        <span>I have read and agree with the above.</span>
      </p>

      <h2>Checking your understanding</h2>

      <p>To start the experiment, please check only the options that are true:</p>

      <ul className="invisible-list">
        <li><input type="checkbox" value={q1} onChange={() => setQ1(!q1)} /><span>You will compare different solutions to algebra problems.</span></li>
        <li><input type="checkbox" value={q2} onChange={() => setQ2(!q2)} /><span>The solutions to be evaluated come from human students.</span></li>
        <li><input type="checkbox" value={q3} onChange={() => setQ3(!q3)} /><span>In the equation x + 1 = 9, one solution is x = 5</span></li>
        <li><input type="checkbox" value={q4} onChange={() => setQ4(!q4)} /><span>In the equation x - 2 = 8, one solution is x = 10</span></li>
      </ul>

      <button disabled={!consent} onClick={next}>Continue</button>
    </div>
  );
};
export default Instructions;
